# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'legtool/legtool_main_window.ui'
#
# Created: Wed Jul  2 20:43:40 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LegToolMainWindow(object):
    def setupUi(self, LegToolMainWindow):
        LegToolMainWindow.setObjectName("LegToolMainWindow")
        LegToolMainWindow.resize(1014, 929)
        self.centralwidget = QtGui.QWidget(LegToolMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.servoTab = QtGui.QWidget()
        self.servoTab.setObjectName("servoTab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.servoTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.configurationGroup = QtGui.QGroupBox(self.servoTab)
        self.configurationGroup.setObjectName("configurationGroup")
        self.formLayout_9 = QtGui.QFormLayout(self.configurationGroup)
        self.formLayout_9.setObjectName("formLayout_9")
        self.typeLabel = QtGui.QLabel(self.configurationGroup)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.typeLabel)
        self.typeCombo = QtGui.QComboBox(self.configurationGroup)
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.typeCombo)
        self.serialPortLabel = QtGui.QLabel(self.configurationGroup)
        self.serialPortLabel.setObjectName("serialPortLabel")
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.serialPortLabel)
        self.serialPortCombo = QtGui.QComboBox(self.configurationGroup)
        self.serialPortCombo.setEditable(True)
        self.serialPortCombo.setObjectName("serialPortCombo")
        self.serialPortCombo.addItem("")
        self.serialPortCombo.addItem("")
        self.serialPortCombo.addItem("")
        self.serialPortCombo.addItem("")
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.serialPortCombo)
        self.modelLabel = QtGui.QLabel(self.configurationGroup)
        self.modelLabel.setObjectName("modelLabel")
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.modelLabel)
        self.configureGazeboButton = QtGui.QPushButton(self.configurationGroup)
        self.configureGazeboButton.setObjectName("configureGazeboButton")
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.FieldRole, self.configureGazeboButton)
        self.connectButton = QtGui.QPushButton(self.configurationGroup)
        self.connectButton.setObjectName("connectButton")
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.FieldRole, self.connectButton)
        self.line = QtGui.QFrame(self.configurationGroup)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.SpanningRole, self.line)
        self.statusLabel = QtGui.QLabel(self.configurationGroup)
        self.statusLabel.setObjectName("statusLabel")
        self.formLayout_9.setWidget(5, QtGui.QFormLayout.LabelRole, self.statusLabel)
        self.statusText = QtGui.QLabel(self.configurationGroup)
        self.statusText.setObjectName("statusText")
        self.formLayout_9.setWidget(5, QtGui.QFormLayout.FieldRole, self.statusText)
        self.servoCountLabel = QtGui.QLabel(self.configurationGroup)
        self.servoCountLabel.setObjectName("servoCountLabel")
        self.formLayout_9.setWidget(6, QtGui.QFormLayout.LabelRole, self.servoCountLabel)
        self.servoCountSpin = QtGui.QSpinBox(self.configurationGroup)
        self.servoCountSpin.setMinimum(1)
        self.servoCountSpin.setMaximum(253)
        self.servoCountSpin.setProperty("value", 14)
        self.servoCountSpin.setObjectName("servoCountSpin")
        self.formLayout_9.setWidget(6, QtGui.QFormLayout.FieldRole, self.servoCountSpin)
        spacerItem = QtGui.QSpacerItem(20, 276, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_9.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem)
        self.verticalLayout_14.addWidget(self.configurationGroup)
        self.posesGroup = QtGui.QGroupBox(self.servoTab)
        self.posesGroup.setObjectName("posesGroup")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.posesGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.poseList = QtGui.QListWidget(self.posesGroup)
        self.poseList.setObjectName("poseList")
        self.verticalLayout_2.addWidget(self.poseList)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.addPoseButton = QtGui.QPushButton(self.posesGroup)
        self.addPoseButton.setObjectName("addPoseButton")
        self.gridLayout_4.addWidget(self.addPoseButton, 0, 0, 1, 1)
        self.removePoseButton = QtGui.QPushButton(self.posesGroup)
        self.removePoseButton.setObjectName("removePoseButton")
        self.gridLayout_4.addWidget(self.removePoseButton, 0, 1, 1, 1)
        self.moveToPoseButton = QtGui.QPushButton(self.posesGroup)
        self.moveToPoseButton.setObjectName("moveToPoseButton")
        self.gridLayout_4.addWidget(self.moveToPoseButton, 1, 0, 1, 1)
        self.updatePoseButton = QtGui.QPushButton(self.posesGroup)
        self.updatePoseButton.setObjectName("updatePoseButton")
        self.gridLayout_4.addWidget(self.updatePoseButton, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_14.addWidget(self.posesGroup)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.controlGroup = QtGui.QGroupBox(self.servoTab)
        self.controlGroup.setObjectName("controlGroup")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.controlGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.powerLabel = QtGui.QLabel(self.controlGroup)
        self.powerLabel.setObjectName("powerLabel")
        self.horizontalLayout.addWidget(self.powerLabel)
        self.powerCombo = QtGui.QComboBox(self.controlGroup)
        self.powerCombo.setObjectName("powerCombo")
        self.powerCombo.addItem("")
        self.powerCombo.addItem("")
        self.powerCombo.addItem("")
        self.horizontalLayout.addWidget(self.powerCombo)
        self.captureCurrentButton = QtGui.QPushButton(self.controlGroup)
        self.captureCurrentButton.setObjectName("captureCurrentButton")
        self.horizontalLayout.addWidget(self.captureCurrentButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.controlGroup)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.scrollArea = QtGui.QScrollArea(self.controlGroup)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContents = QtGui.QWidget()
        self.scrollContents.setGeometry(QtCore.QRect(0, 0, 701, 745))
        self.scrollContents.setObjectName("scrollContents")
        self.scrollArea.setWidget(self.scrollContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.controlGroup)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 6)
        self.tabWidget.addTab(self.servoTab, "")
        self.ikConfigTab = QtGui.QWidget()
        self.ikConfigTab.setObjectName("ikConfigTab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.ikConfigTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.configurationGroup_2 = QtGui.QGroupBox(self.ikConfigTab)
        self.configurationGroup_2.setObjectName("configurationGroup_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.configurationGroup_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.femurSignCombo = QtGui.QComboBox(self.configurationGroup_2)
        self.femurSignCombo.setObjectName("femurSignCombo")
        self.femurSignCombo.addItem("")
        self.femurSignCombo.addItem("")
        self.gridLayout_2.addWidget(self.femurSignCombo, 4, 2, 1, 1)
        self.legLabel = QtGui.QLabel(self.configurationGroup_2)
        self.legLabel.setObjectName("legLabel")
        self.gridLayout_2.addWidget(self.legLabel, 0, 0, 1, 1)
        self.legSpin = QtGui.QSpinBox(self.configurationGroup_2)
        self.legSpin.setMinimum(0)
        self.legSpin.setMaximum(5)
        self.legSpin.setProperty("value", 0)
        self.legSpin.setObjectName("legSpin")
        self.gridLayout_2.addWidget(self.legSpin, 0, 2, 1, 1)
        self.line_3 = QtGui.QFrame(self.configurationGroup_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 1, 0, 1, 3)
        self.legPresentCombo = QtGui.QComboBox(self.configurationGroup_2)
        self.legPresentCombo.setObjectName("legPresentCombo")
        self.legPresentCombo.addItem("")
        self.legPresentCombo.addItem("")
        self.gridLayout_2.addWidget(self.legPresentCombo, 2, 2, 1, 1)
        self.coxaLabel = QtGui.QLabel(self.configurationGroup_2)
        self.coxaLabel.setObjectName("coxaLabel")
        self.gridLayout_2.addWidget(self.coxaLabel, 3, 0, 1, 1)
        self.coxaServoSpin = QtGui.QSpinBox(self.configurationGroup_2)
        self.coxaServoSpin.setObjectName("coxaServoSpin")
        self.gridLayout_2.addWidget(self.coxaServoSpin, 3, 1, 1, 1)
        self.coxaSignCombo = QtGui.QComboBox(self.configurationGroup_2)
        self.coxaSignCombo.setObjectName("coxaSignCombo")
        self.coxaSignCombo.addItem("")
        self.coxaSignCombo.addItem("")
        self.gridLayout_2.addWidget(self.coxaSignCombo, 3, 2, 1, 1)
        self.femurLabel = QtGui.QLabel(self.configurationGroup_2)
        self.femurLabel.setObjectName("femurLabel")
        self.gridLayout_2.addWidget(self.femurLabel, 4, 0, 1, 1)
        self.femurServoSpin = QtGui.QSpinBox(self.configurationGroup_2)
        self.femurServoSpin.setObjectName("femurServoSpin")
        self.gridLayout_2.addWidget(self.femurServoSpin, 4, 1, 1, 1)
        self.tibiaLabel = QtGui.QLabel(self.configurationGroup_2)
        self.tibiaLabel.setObjectName("tibiaLabel")
        self.gridLayout_2.addWidget(self.tibiaLabel, 5, 0, 1, 1)
        self.tibiaServoSpin = QtGui.QSpinBox(self.configurationGroup_2)
        self.tibiaServoSpin.setObjectName("tibiaServoSpin")
        self.gridLayout_2.addWidget(self.tibiaServoSpin, 5, 1, 1, 1)
        self.tibiaSignCombo = QtGui.QComboBox(self.configurationGroup_2)
        self.tibiaSignCombo.setObjectName("tibiaSignCombo")
        self.tibiaSignCombo.addItem("")
        self.tibiaSignCombo.addItem("")
        self.gridLayout_2.addWidget(self.tibiaSignCombo, 5, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 47, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.configurationGroup_2)
        self.limitPosesGroup = QtGui.QGroupBox(self.ikConfigTab)
        self.limitPosesGroup.setObjectName("limitPosesGroup")
        self.gridLayout_3 = QtGui.QGridLayout(self.limitPosesGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.idleLabel = QtGui.QLabel(self.limitPosesGroup)
        self.idleLabel.setObjectName("idleLabel")
        self.gridLayout_3.addWidget(self.idleLabel, 0, 0, 1, 1)
        self.idleCombo = QtGui.QComboBox(self.limitPosesGroup)
        self.idleCombo.setObjectName("idleCombo")
        self.gridLayout_3.addWidget(self.idleCombo, 0, 1, 1, 1)
        self.minimumLabel = QtGui.QLabel(self.limitPosesGroup)
        self.minimumLabel.setObjectName("minimumLabel")
        self.gridLayout_3.addWidget(self.minimumLabel, 1, 0, 1, 1)
        self.minimumCombo = QtGui.QComboBox(self.limitPosesGroup)
        self.minimumCombo.setObjectName("minimumCombo")
        self.gridLayout_3.addWidget(self.minimumCombo, 1, 1, 1, 1)
        self.maximumLabel = QtGui.QLabel(self.limitPosesGroup)
        self.maximumLabel.setObjectName("maximumLabel")
        self.gridLayout_3.addWidget(self.maximumLabel, 2, 0, 1, 1)
        self.maximumCombo = QtGui.QComboBox(self.limitPosesGroup)
        self.maximumCombo.setObjectName("maximumCombo")
        self.gridLayout_3.addWidget(self.maximumCombo, 2, 1, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.limitPosesGroup)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 3, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.limitPosesGroup)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtGui.QGroupBox(self.ikConfigTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.xOffsetLabel = QtGui.QLabel(self.groupBox_3)
        self.xOffsetLabel.setObjectName("xOffsetLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.xOffsetLabel)
        self.xOffsetSpin = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.xOffsetSpin.setMinimum(-500.0)
        self.xOffsetSpin.setMaximum(500.0)
        self.xOffsetSpin.setObjectName("xOffsetSpin")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.xOffsetSpin)
        self.yOffsetLabel = QtGui.QLabel(self.groupBox_3)
        self.yOffsetLabel.setObjectName("yOffsetLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.yOffsetLabel)
        self.yOffsetSpin = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.yOffsetSpin.setMinimum(-500.0)
        self.yOffsetSpin.setMaximum(500.0)
        self.yOffsetSpin.setObjectName("yOffsetSpin")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.yOffsetSpin)
        self.zOffsetLabel = QtGui.QLabel(self.groupBox_3)
        self.zOffsetLabel.setObjectName("zOffsetLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.zOffsetLabel)
        self.zOffsetSpin = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.zOffsetSpin.setMinimum(-500.0)
        self.zOffsetSpin.setMaximum(500.0)
        self.zOffsetSpin.setObjectName("zOffsetSpin")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.zOffsetSpin)
        spacerItem4 = QtGui.QSpacerItem(69, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem4)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.ikConfigTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.coxaLengthLabel = QtGui.QLabel(self.groupBox_4)
        self.coxaLengthLabel.setObjectName("coxaLengthLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.coxaLengthLabel)
        self.coxaLengthSpin = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.coxaLengthSpin.setDecimals(0)
        self.coxaLengthSpin.setMinimum(1.0)
        self.coxaLengthSpin.setMaximum(200.0)
        self.coxaLengthSpin.setProperty("value", 50.0)
        self.coxaLengthSpin.setObjectName("coxaLengthSpin")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.coxaLengthSpin)
        self.femurLengthLabel = QtGui.QLabel(self.groupBox_4)
        self.femurLengthLabel.setObjectName("femurLengthLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.femurLengthLabel)
        self.femurLengthSpin = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.femurLengthSpin.setDecimals(0)
        self.femurLengthSpin.setMinimum(1.0)
        self.femurLengthSpin.setMaximum(200.0)
        self.femurLengthSpin.setProperty("value", 50.0)
        self.femurLengthSpin.setObjectName("femurLengthSpin")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.femurLengthSpin)
        self.tibiaLengthLabel = QtGui.QLabel(self.groupBox_4)
        self.tibiaLengthLabel.setObjectName("tibiaLengthLabel")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.tibiaLengthLabel)
        self.tibiaLengthSpin = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.tibiaLengthSpin.setDecimals(0)
        self.tibiaLengthSpin.setMinimum(1.0)
        self.tibiaLengthSpin.setMaximum(200.0)
        self.tibiaLengthSpin.setProperty("value", 50.0)
        self.tibiaLengthSpin.setObjectName("tibiaLengthSpin")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.tibiaLengthSpin)
        spacerItem5 = QtGui.QSpacerItem(53, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem5)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.groupBox_5 = QtGui.QGroupBox(self.ikConfigTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.planeLabel = QtGui.QLabel(self.groupBox_5)
        self.planeLabel.setObjectName("planeLabel")
        self.gridLayout_5.addWidget(self.planeLabel, 0, 0, 1, 1)
        self.planeCombo = QtGui.QComboBox(self.groupBox_5)
        self.planeCombo.setObjectName("planeCombo")
        self.planeCombo.addItem("")
        self.planeCombo.addItem("")
        self.planeCombo.addItem("")
        self.gridLayout_5.addWidget(self.planeCombo, 0, 1, 1, 2)
        self.scaleLabel = QtGui.QLabel(self.groupBox_5)
        self.scaleLabel.setObjectName("scaleLabel")
        self.gridLayout_5.addWidget(self.scaleLabel, 1, 0, 1, 1)
        self.lengthScaleSpin = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.lengthScaleSpin.setDecimals(0)
        self.lengthScaleSpin.setMinimum(10.0)
        self.lengthScaleSpin.setMaximum(500.0)
        self.lengthScaleSpin.setSingleStep(10.0)
        self.lengthScaleSpin.setProperty("value", 50.0)
        self.lengthScaleSpin.setObjectName("lengthScaleSpin")
        self.gridLayout_5.addWidget(self.lengthScaleSpin, 1, 1, 1, 2)
        self.speedScaleLabel = QtGui.QLabel(self.groupBox_5)
        self.speedScaleLabel.setObjectName("speedScaleLabel")
        self.gridLayout_5.addWidget(self.speedScaleLabel, 2, 0, 1, 1)
        self.speedScaleSpin = QtGui.QSpinBox(self.groupBox_5)
        self.speedScaleSpin.setMinimum(10)
        self.speedScaleSpin.setMaximum(5000)
        self.speedScaleSpin.setSingleStep(20)
        self.speedScaleSpin.setProperty("value", 500)
        self.speedScaleSpin.setObjectName("speedScaleSpin")
        self.gridLayout_5.addWidget(self.speedScaleSpin, 2, 1, 1, 1)
        self.speedAxisCombo = QtGui.QComboBox(self.groupBox_5)
        self.speedAxisCombo.setObjectName("speedAxisCombo")
        self.speedAxisCombo.addItem("")
        self.speedAxisCombo.addItem("")
        self.speedAxisCombo.addItem("")
        self.speedAxisCombo.addItem("")
        self.gridLayout_5.addWidget(self.speedAxisCombo, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_5)
        self.line_4 = QtGui.QFrame(self.groupBox_5)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.ikTestView = QtGui.QGraphicsView(self.groupBox_5)
        self.ikTestView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ikTestView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ikTestView.setObjectName("ikTestView")
        self.verticalLayout_4.addWidget(self.ikTestView)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.ikConfigTab, "")
        self.gaitConfigTab = QtGui.QWidget()
        self.gaitConfigTab.setObjectName("gaitConfigTab")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.gaitConfigTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.mountingGroup = QtGui.QGroupBox(self.gaitConfigTab)
        self.mountingGroup.setObjectName("mountingGroup")
        self.formLayout_3 = QtGui.QFormLayout(self.mountingGroup)
        self.formLayout_3.setObjectName("formLayout_3")
        self.gaitLegLabel = QtGui.QLabel(self.mountingGroup)
        self.gaitLegLabel.setObjectName("gaitLegLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.gaitLegLabel)
        self.gaitLegList = QtGui.QListWidget(self.mountingGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaitLegList.sizePolicy().hasHeightForWidth())
        self.gaitLegList.setSizePolicy(sizePolicy)
        self.gaitLegList.setMaximumSize(QtCore.QSize(16777215, 80))
        self.gaitLegList.setObjectName("gaitLegList")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.gaitLegList)
        self.line_5 = QtGui.QFrame(self.mountingGroup)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line_5)
        self.label_2 = QtGui.QLabel(self.mountingGroup)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.mountingLegXSpin = QtGui.QDoubleSpinBox(self.mountingGroup)
        self.mountingLegXSpin.setMinimum(-1000.0)
        self.mountingLegXSpin.setMaximum(1000.0)
        self.mountingLegXSpin.setSingleStep(5.0)
        self.mountingLegXSpin.setProperty("value", 0.0)
        self.mountingLegXSpin.setObjectName("mountingLegXSpin")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.mountingLegXSpin)
        self.label_3 = QtGui.QLabel(self.mountingGroup)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.mountingLegYSpin = QtGui.QDoubleSpinBox(self.mountingGroup)
        self.mountingLegYSpin.setMinimum(-1000.0)
        self.mountingLegYSpin.setMaximum(1000.0)
        self.mountingLegYSpin.setSingleStep(10.0)
        self.mountingLegYSpin.setObjectName("mountingLegYSpin")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.mountingLegYSpin)
        self.label_4 = QtGui.QLabel(self.mountingGroup)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.mountingLegZSpin = QtGui.QDoubleSpinBox(self.mountingGroup)
        self.mountingLegZSpin.setMaximum(1000.0)
        self.mountingLegZSpin.setSingleStep(10.0)
        self.mountingLegZSpin.setObjectName("mountingLegZSpin")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.mountingLegZSpin)
        self.verticalLayout_13.addWidget(self.mountingGroup)
        self.bodyCogGroup = QtGui.QGroupBox(self.gaitConfigTab)
        self.bodyCogGroup.setObjectName("bodyCogGroup")
        self.formLayout_4 = QtGui.QFormLayout(self.bodyCogGroup)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtGui.QLabel(self.bodyCogGroup)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.bodyCogXSpin = QtGui.QDoubleSpinBox(self.bodyCogGroup)
        self.bodyCogXSpin.setDecimals(1)
        self.bodyCogXSpin.setMinimum(-500.0)
        self.bodyCogXSpin.setMaximum(500.0)
        self.bodyCogXSpin.setSingleStep(10.0)
        self.bodyCogXSpin.setObjectName("bodyCogXSpin")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.bodyCogXSpin)
        self.label_14 = QtGui.QLabel(self.bodyCogGroup)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.bodyCogYSpin = QtGui.QDoubleSpinBox(self.bodyCogGroup)
        self.bodyCogYSpin.setDecimals(1)
        self.bodyCogYSpin.setMinimum(-500.0)
        self.bodyCogYSpin.setMaximum(500.0)
        self.bodyCogYSpin.setSingleStep(10.0)
        self.bodyCogYSpin.setObjectName("bodyCogYSpin")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.bodyCogYSpin)
        self.label_15 = QtGui.QLabel(self.bodyCogGroup)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.bodyCogZSpin = QtGui.QDoubleSpinBox(self.bodyCogGroup)
        self.bodyCogZSpin.setDecimals(1)
        self.bodyCogZSpin.setMinimum(-500.0)
        self.bodyCogZSpin.setMaximum(500.0)
        self.bodyCogZSpin.setSingleStep(10.0)
        self.bodyCogZSpin.setObjectName("bodyCogZSpin")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.bodyCogZSpin)
        self.verticalLayout_13.addWidget(self.bodyCogGroup)
        self.idlePositionGroup = QtGui.QGroupBox(self.gaitConfigTab)
        self.idlePositionGroup.setObjectName("idlePositionGroup")
        self.formLayout_5 = QtGui.QFormLayout(self.idlePositionGroup)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_10 = QtGui.QLabel(self.idlePositionGroup)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.idlePositionXSpin = QtGui.QDoubleSpinBox(self.idlePositionGroup)
        self.idlePositionXSpin.setMaximum(1000.0)
        self.idlePositionXSpin.setSingleStep(10.0)
        self.idlePositionXSpin.setObjectName("idlePositionXSpin")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.idlePositionXSpin)
        self.label_11 = QtGui.QLabel(self.idlePositionGroup)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.idlePositionYSpin = QtGui.QDoubleSpinBox(self.idlePositionGroup)
        self.idlePositionYSpin.setMinimum(-1000.0)
        self.idlePositionYSpin.setMaximum(1000.0)
        self.idlePositionYSpin.setSingleStep(10.0)
        self.idlePositionYSpin.setObjectName("idlePositionYSpin")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.idlePositionYSpin)
        self.label_12 = QtGui.QLabel(self.idlePositionGroup)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.idlePositionZSpin = QtGui.QDoubleSpinBox(self.idlePositionGroup)
        self.idlePositionZSpin.setMinimum(-1000.0)
        self.idlePositionZSpin.setMaximum(1000.0)
        self.idlePositionZSpin.setSingleStep(10.0)
        self.idlePositionZSpin.setObjectName("idlePositionZSpin")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.idlePositionZSpin)
        self.verticalLayout_13.addWidget(self.idlePositionGroup)
        self.gaitGroup = QtGui.QGroupBox(self.gaitConfigTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaitGroup.sizePolicy().hasHeightForWidth())
        self.gaitGroup.setSizePolicy(sizePolicy)
        self.gaitGroup.setObjectName("gaitGroup")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.gaitGroup)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox = QtGui.QComboBox(self.gaitGroup)
        self.comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox)
        self.line_6 = QtGui.QFrame(self.gaitGroup)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_11.addWidget(self.line_6)
        self.toolBox = QtGui.QToolBox(self.gaitGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(220, 240))
        self.toolBox.setStyleSheet("QScrollBar:horizontal {\n"
"  height: 0px;\n"
"  width: 0px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  height: 0px;\n"
"  width: 0px;\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 225, 174))
        self.page.setObjectName("page")
        self.formLayout_6 = QtGui.QFormLayout(self.page)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.maxCycleTimeSpin = QtGui.QDoubleSpinBox(self.page)
        self.maxCycleTimeSpin.setMaximum(20.0)
        self.maxCycleTimeSpin.setSingleStep(0.1)
        self.maxCycleTimeSpin.setProperty("value", 4.0)
        self.maxCycleTimeSpin.setObjectName("maxCycleTimeSpin")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxCycleTimeSpin)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.liftHeightSpin = QtGui.QDoubleSpinBox(self.page)
        self.liftHeightSpin.setMinimum(1.0)
        self.liftHeightSpin.setMaximum(100.0)
        self.liftHeightSpin.setProperty("value", 10.0)
        self.liftHeightSpin.setObjectName("liftHeightSpin")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.liftHeightSpin)
        self.label_8 = QtGui.QLabel(self.page)
        self.label_8.setObjectName("label_8")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.swingPercentSpin = QtGui.QDoubleSpinBox(self.page)
        self.swingPercentSpin.setMaximum(200.0)
        self.swingPercentSpin.setProperty("value", 50.0)
        self.swingPercentSpin.setObjectName("swingPercentSpin")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.swingPercentSpin)
        self.label_9 = QtGui.QLabel(self.page)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.positionMarginSpin = QtGui.QDoubleSpinBox(self.page)
        self.positionMarginSpin.setMinimum(1.0)
        self.positionMarginSpin.setMaximum(100.0)
        self.positionMarginSpin.setProperty("value", 80.0)
        self.positionMarginSpin.setObjectName("positionMarginSpin")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.positionMarginSpin)
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName("label")
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label)
        self.bodyZOffsetSpin = QtGui.QDoubleSpinBox(self.page)
        self.bodyZOffsetSpin.setMinimum(-1000.0)
        self.bodyZOffsetSpin.setMaximum(1000.0)
        self.bodyZOffsetSpin.setSingleStep(10.0)
        self.bodyZOffsetSpin.setProperty("value", 60.0)
        self.bodyZOffsetSpin.setObjectName("bodyZOffsetSpin")
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.bodyZOffsetSpin)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.legOrderEdit = QtGui.QLineEdit(self.page)
        self.legOrderEdit.setObjectName("legOrderEdit")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.legOrderEdit)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 209, 119))
        self.page_2.setObjectName("page_2")
        self.formLayout_7 = QtGui.QFormLayout(self.page_2)
        self.formLayout_7.setObjectName("formLayout_7")
        self.staticEnableCheck = QtGui.QCheckBox(self.page_2)
        self.staticEnableCheck.setObjectName("staticEnableCheck")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.SpanningRole, self.staticEnableCheck)
        self.label_30 = QtGui.QLabel(self.page_2)
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_30)
        self.staticCenterSpin = QtGui.QDoubleSpinBox(self.page_2)
        self.staticCenterSpin.setDecimals(1)
        self.staticCenterSpin.setMaximum(1000.0)
        self.staticCenterSpin.setSingleStep(1.0)
        self.staticCenterSpin.setProperty("value", 3.0)
        self.staticCenterSpin.setObjectName("staticCenterSpin")
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.staticCenterSpin)
        self.label_31 = QtGui.QLabel(self.page_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_31)
        self.staticStableSpin = QtGui.QDoubleSpinBox(self.page_2)
        self.staticStableSpin.setDecimals(1)
        self.staticStableSpin.setMaximum(500.0)
        self.staticStableSpin.setSingleStep(1.0)
        self.staticStableSpin.setProperty("value", 10.0)
        self.staticStableSpin.setObjectName("staticStableSpin")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.staticStableSpin)
        self.label_32 = QtGui.QLabel(self.page_2)
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_32)
        self.staticMarginSpin = QtGui.QDoubleSpinBox(self.page_2)
        self.staticMarginSpin.setDecimals(1)
        self.staticMarginSpin.setMinimum(1.0)
        self.staticMarginSpin.setMaximum(1000.0)
        self.staticMarginSpin.setSingleStep(5.0)
        self.staticMarginSpin.setProperty("value", 30.0)
        self.staticMarginSpin.setObjectName("staticMarginSpin")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.staticMarginSpin)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_11.addWidget(self.toolBox)
        self.line_7 = QtGui.QFrame(self.gaitGroup)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_11.addWidget(self.line_7)
        self.gaitOptionsBrowser = QtGui.QTextBrowser(self.gaitGroup)
        self.gaitOptionsBrowser.setMaximumSize(QtCore.QSize(16777215, 60))
        self.gaitOptionsBrowser.setObjectName("gaitOptionsBrowser")
        self.verticalLayout_11.addWidget(self.gaitOptionsBrowser)
        self.verticalLayout_13.addWidget(self.gaitGroup)
        spacerItem7 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gaitGraphGroup = QtGui.QGroupBox(self.gaitConfigTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaitGraphGroup.sizePolicy().hasHeightForWidth())
        self.gaitGraphGroup.setSizePolicy(sizePolicy)
        self.gaitGraphGroup.setObjectName("gaitGraphGroup")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.gaitGraphGroup)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gaitGraphView = QtGui.QGraphicsView(self.gaitGraphGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaitGraphView.sizePolicy().hasHeightForWidth())
        self.gaitGraphView.setSizePolicy(sizePolicy)
        self.gaitGraphView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gaitGraphView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gaitGraphView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gaitGraphView.setObjectName("gaitGraphView")
        self.verticalLayout_7.addWidget(self.gaitGraphView)
        self.verticalLayout_10.addWidget(self.gaitGraphGroup)
        self.playbackGroup = QtGui.QGroupBox(self.gaitConfigTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playbackGroup.sizePolicy().hasHeightForWidth())
        self.playbackGroup.setSizePolicy(sizePolicy)
        self.playbackGroup.setObjectName("playbackGroup")
        self.gridLayout_7 = QtGui.QGridLayout(self.playbackGroup)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.playbackBeginLabel = QtGui.QLabel(self.playbackGroup)
        self.playbackBeginLabel.setObjectName("playbackBeginLabel")
        self.gridLayout_7.addWidget(self.playbackBeginLabel, 0, 0, 1, 1)
        self.playbackBeginCombo = QtGui.QComboBox(self.playbackGroup)
        self.playbackBeginCombo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playbackBeginCombo.setObjectName("playbackBeginCombo")
        self.playbackBeginCombo.addItem("")
        self.playbackBeginCombo.addItem("")
        self.gridLayout_7.addWidget(self.playbackBeginCombo, 0, 1, 1, 1)
        self.playbackPhaseSlider = QtGui.QSlider(self.playbackGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playbackPhaseSlider.sizePolicy().hasHeightForWidth())
        self.playbackPhaseSlider.setSizePolicy(sizePolicy)
        self.playbackPhaseSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.playbackPhaseSlider.setMaximum(200)
        self.playbackPhaseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playbackPhaseSlider.setObjectName("playbackPhaseSlider")
        self.gridLayout_7.addWidget(self.playbackPhaseSlider, 1, 0, 1, 2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.playbackSingleButton = QtGui.QPushButton(self.playbackGroup)
        self.playbackSingleButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playbackSingleButton.setCheckable(True)
        self.playbackSingleButton.setChecked(False)
        self.playbackSingleButton.setObjectName("playbackSingleButton")
        self.horizontalLayout_6.addWidget(self.playbackSingleButton)
        self.playbackRepeatButton = QtGui.QPushButton(self.playbackGroup)
        self.playbackRepeatButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playbackRepeatButton.setCheckable(True)
        self.playbackRepeatButton.setObjectName("playbackRepeatButton")
        self.horizontalLayout_6.addWidget(self.playbackRepeatButton)
        self.playbackSlowRepeatButton = QtGui.QPushButton(self.playbackGroup)
        self.playbackSlowRepeatButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playbackSlowRepeatButton.setCheckable(True)
        self.playbackSlowRepeatButton.setObjectName("playbackSlowRepeatButton")
        self.horizontalLayout_6.addWidget(self.playbackSlowRepeatButton)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 2, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.playbackCaptureButton = QtGui.QPushButton(self.playbackGroup)
        self.playbackCaptureButton.setObjectName("playbackCaptureButton")
        self.horizontalLayout_4.addWidget(self.playbackCaptureButton)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 3, 0, 1, 2)
        self.verticalLayout_10.addWidget(self.playbackGroup)
        self.groupBox = QtGui.QGroupBox(self.gaitConfigTab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_8 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.commandXSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandXSpin.setDecimals(0)
        self.commandXSpin.setMinimum(-1000.0)
        self.commandXSpin.setMaximum(1000.0)
        self.commandXSpin.setSingleStep(10.0)
        self.commandXSpin.setObjectName("commandXSpin")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.commandXSpin)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.commandYSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandYSpin.setDecimals(0)
        self.commandYSpin.setMinimum(-1000.0)
        self.commandYSpin.setMaximum(1000.0)
        self.commandYSpin.setSingleStep(10.0)
        self.commandYSpin.setObjectName("commandYSpin")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.commandYSpin)
        self.commandRotSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandRotSpin.setDecimals(1)
        self.commandRotSpin.setMinimum(-50.0)
        self.commandRotSpin.setMaximum(50.0)
        self.commandRotSpin.setObjectName("commandRotSpin")
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.commandRotSpin)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_21)
        self.commandBodyXSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandBodyXSpin.setDecimals(0)
        self.commandBodyXSpin.setMinimum(-1000.0)
        self.commandBodyXSpin.setMaximum(1000.0)
        self.commandBodyXSpin.setSingleStep(10.0)
        self.commandBodyXSpin.setObjectName("commandBodyXSpin")
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.commandBodyXSpin)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_22)
        self.commandBodyYSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandBodyYSpin.setDecimals(0)
        self.commandBodyYSpin.setMinimum(-1000.0)
        self.commandBodyYSpin.setMaximum(1000.0)
        self.commandBodyYSpin.setSingleStep(10.0)
        self.commandBodyYSpin.setObjectName("commandBodyYSpin")
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.FieldRole, self.commandBodyYSpin)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_23)
        self.commandBodyZSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandBodyZSpin.setDecimals(0)
        self.commandBodyZSpin.setMinimum(-1000.0)
        self.commandBodyZSpin.setMaximum(1000.0)
        self.commandBodyZSpin.setSingleStep(10.0)
        self.commandBodyZSpin.setObjectName("commandBodyZSpin")
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.FieldRole, self.commandBodyZSpin)
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.formLayout_8.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_24)
        self.commandPitchSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandPitchSpin.setDecimals(1)
        self.commandPitchSpin.setMinimum(-90.0)
        self.commandPitchSpin.setMaximum(90.0)
        self.commandPitchSpin.setObjectName("commandPitchSpin")
        self.formLayout_8.setWidget(6, QtGui.QFormLayout.FieldRole, self.commandPitchSpin)
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.formLayout_8.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_25)
        self.commandRollSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandRollSpin.setDecimals(1)
        self.commandRollSpin.setMinimum(-90.0)
        self.commandRollSpin.setMaximum(90.0)
        self.commandRollSpin.setObjectName("commandRollSpin")
        self.formLayout_8.setWidget(7, QtGui.QFormLayout.FieldRole, self.commandRollSpin)
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.formLayout_8.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_26)
        self.commandYawSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.commandYawSpin.setDecimals(1)
        self.commandYawSpin.setMinimum(-180.0)
        self.commandYawSpin.setMaximum(180.0)
        self.commandYawSpin.setObjectName("commandYawSpin")
        self.formLayout_8.setWidget(8, QtGui.QFormLayout.FieldRole, self.commandYawSpin)
        self.commandResetButton = QtGui.QPushButton(self.groupBox)
        self.commandResetButton.setObjectName("commandResetButton")
        self.formLayout_8.setWidget(9, QtGui.QFormLayout.SpanningRole, self.commandResetButton)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_20)
        self.verticalLayout_10.addWidget(self.groupBox)
        spacerItem9 = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.geometryGroup = QtGui.QGroupBox(self.gaitConfigTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geometryGroup.sizePolicy().hasHeightForWidth())
        self.geometryGroup.setSizePolicy(sizePolicy)
        self.geometryGroup.setObjectName("geometryGroup")
        self.verticalLayout = QtGui.QVBoxLayout(self.geometryGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.geometryFrameCombo = QtGui.QComboBox(self.geometryGroup)
        self.geometryFrameCombo.setObjectName("geometryFrameCombo")
        self.geometryFrameCombo.addItem("")
        self.geometryFrameCombo.addItem("")
        self.geometryFrameCombo.addItem("")
        self.gridLayout_6.addWidget(self.geometryFrameCombo, 0, 0, 1, 1)
        self.geometryProjectionCombo = QtGui.QComboBox(self.geometryGroup)
        self.geometryProjectionCombo.setObjectName("geometryProjectionCombo")
        self.geometryProjectionCombo.addItem("")
        self.geometryProjectionCombo.addItem("")
        self.geometryProjectionCombo.addItem("")
        self.gridLayout_6.addWidget(self.geometryProjectionCombo, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.geometryGroup)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 1, 0, 1, 1)
        self.geometryScaleSpin = QtGui.QDoubleSpinBox(self.geometryGroup)
        self.geometryScaleSpin.setDecimals(1)
        self.geometryScaleSpin.setMaximum(1000000.0)
        self.geometryScaleSpin.setSingleStep(50.0)
        self.geometryScaleSpin.setProperty("value", 300.0)
        self.geometryScaleSpin.setObjectName("geometryScaleSpin")
        self.gridLayout_6.addWidget(self.geometryScaleSpin, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gaitGeometryView = QtGui.QGraphicsView(self.geometryGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaitGeometryView.sizePolicy().hasHeightForWidth())
        self.gaitGeometryView.setSizePolicy(sizePolicy)
        self.gaitGeometryView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gaitGeometryView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gaitGeometryView.setObjectName("gaitGeometryView")
        self.verticalLayout.addWidget(self.gaitGeometryView)
        self.verticalLayout_9.addWidget(self.geometryGroup)
        self.commandGroup = QtGui.QGroupBox(self.gaitConfigTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandGroup.sizePolicy().hasHeightForWidth())
        self.commandGroup.setSizePolicy(sizePolicy)
        self.commandGroup.setObjectName("commandGroup")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.commandGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_18 = QtGui.QLabel(self.commandGroup)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 0, 0, 1, 1)
        self.commandXCombo = QtGui.QComboBox(self.commandGroup)
        self.commandXCombo.setObjectName("commandXCombo")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.commandXCombo.addItem("")
        self.gridLayout_8.addWidget(self.commandXCombo, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.commandGroup)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 2, 1, 1)
        self.commandXScaleSpin = QtGui.QDoubleSpinBox(self.commandGroup)
        self.commandXScaleSpin.setDecimals(1)
        self.commandXScaleSpin.setMinimum(1.0)
        self.commandXScaleSpin.setMaximum(5000.0)
        self.commandXScaleSpin.setSingleStep(10.0)
        self.commandXScaleSpin.setObjectName("commandXScaleSpin")
        self.gridLayout_8.addWidget(self.commandXScaleSpin, 0, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.commandGroup)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 1, 0, 1, 1)
        self.commandYCombo = QtGui.QComboBox(self.commandGroup)
        self.commandYCombo.setObjectName("commandYCombo")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.commandYCombo.addItem("")
        self.gridLayout_8.addWidget(self.commandYCombo, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.commandGroup)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 1, 2, 1, 1)
        self.commandYScaleSpin = QtGui.QDoubleSpinBox(self.commandGroup)
        self.commandYScaleSpin.setDecimals(1)
        self.commandYScaleSpin.setMinimum(1.0)
        self.commandYScaleSpin.setMaximum(5000.0)
        self.commandYScaleSpin.setSingleStep(10.0)
        self.commandYScaleSpin.setObjectName("commandYScaleSpin")
        self.gridLayout_8.addWidget(self.commandYScaleSpin, 1, 3, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        self.gaitCommandView = QtGui.QGraphicsView(self.commandGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaitCommandView.sizePolicy().hasHeightForWidth())
        self.gaitCommandView.setSizePolicy(sizePolicy)
        self.gaitCommandView.setObjectName("gaitCommandView")
        self.verticalLayout_8.addWidget(self.gaitCommandView)
        self.verticalLayout_9.addWidget(self.commandGroup)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 6)
        self.tabWidget.addTab(self.gaitConfigTab, "")
        self.verticalLayout_12.addWidget(self.tabWidget)
        LegToolMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LegToolMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 20))
        self.menubar.setObjectName("menubar")
        LegToolMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LegToolMainWindow)
        self.statusbar.setObjectName("statusbar")
        LegToolMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LegToolMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.commandYCombo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(LegToolMainWindow)

    def retranslateUi(self, LegToolMainWindow):
        LegToolMainWindow.setWindowTitle(QtGui.QApplication.translate("LegToolMainWindow", "legtool", None, QtGui.QApplication.UnicodeUTF8))
        self.configurationGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "HerkuleX", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Gazebo", None, QtGui.QApplication.UnicodeUTF8))
        self.serialPortLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Serial Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.serialPortCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "/dev/ttyUSB0", None, QtGui.QApplication.UnicodeUTF8))
        self.serialPortCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "/dev/ttyUSB1", None, QtGui.QApplication.UnicodeUTF8))
        self.serialPortCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "/dev/ttyS0", None, QtGui.QApplication.UnicodeUTF8))
        self.serialPortCombo.setItemText(3, QtGui.QApplication.translate("LegToolMainWindow", "/dev/ttyS1", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Gazebo:", None, QtGui.QApplication.UnicodeUTF8))
        self.configureGazeboButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Configure Gazebo", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.statusText.setText(QtGui.QApplication.translate("LegToolMainWindow", "stuff", None, QtGui.QApplication.UnicodeUTF8))
        self.servoCountLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Servo Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.posesGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Poses", None, QtGui.QApplication.UnicodeUTF8))
        self.addPoseButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Add Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.removePoseButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Remove Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.moveToPoseButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Move all Servos", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePoseButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Save all Servos", None, QtGui.QApplication.UnicodeUTF8))
        self.controlGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.powerLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Power:", None, QtGui.QApplication.UnicodeUTF8))
        self.powerCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "Free", None, QtGui.QApplication.UnicodeUTF8))
        self.powerCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Brake", None, QtGui.QApplication.UnicodeUTF8))
        self.powerCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "Drive", None, QtGui.QApplication.UnicodeUTF8))
        self.captureCurrentButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Capture Current", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.servoTab), QtGui.QApplication.translate("LegToolMainWindow", "Servo Control", None, QtGui.QApplication.UnicodeUTF8))
        self.configurationGroup_2.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.femurSignCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "+ Up", None, QtGui.QApplication.UnicodeUTF8))
        self.femurSignCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "- Up", None, QtGui.QApplication.UnicodeUTF8))
        self.legLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Leg:", None, QtGui.QApplication.UnicodeUTF8))
        self.legPresentCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "Present", None, QtGui.QApplication.UnicodeUTF8))
        self.legPresentCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Not Present", None, QtGui.QApplication.UnicodeUTF8))
        self.coxaLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Coxa:", None, QtGui.QApplication.UnicodeUTF8))
        self.coxaSignCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "+ Fwd", None, QtGui.QApplication.UnicodeUTF8))
        self.coxaSignCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "- Fwd", None, QtGui.QApplication.UnicodeUTF8))
        self.femurLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Femur:", None, QtGui.QApplication.UnicodeUTF8))
        self.tibiaLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Tibia:", None, QtGui.QApplication.UnicodeUTF8))
        self.tibiaSignCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "+ Out", None, QtGui.QApplication.UnicodeUTF8))
        self.tibiaSignCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "- Out", None, QtGui.QApplication.UnicodeUTF8))
        self.limitPosesGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Limit Poses", None, QtGui.QApplication.UnicodeUTF8))
        self.idleLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Idle:", None, QtGui.QApplication.UnicodeUTF8))
        self.minimumLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.maximumLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Maximum:", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("LegToolMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NOTE: &quot;Idle&quot; has the following conventions:</p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Coxa is at right angle to direction of forward motion.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Femur is parallel to ground.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tibia is perpendicular to ground.</li></ol></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "IK Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.xOffsetLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "X (right) (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.yOffsetLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Y (forward) (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.zOffsetLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Z (up) (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.coxaLengthLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Coxa Length (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.femurLengthLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Femur Length (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.tibiaLengthLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Tibia Length (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "IK Test (click/hold to actuate)", None, QtGui.QApplication.UnicodeUTF8))
        self.planeLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Plane:", None, QtGui.QApplication.UnicodeUTF8))
        self.planeCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "X/Y (Clockwise/Out)", None, QtGui.QApplication.UnicodeUTF8))
        self.planeCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "X/Z (Clockwise/Up)", None, QtGui.QApplication.UnicodeUTF8))
        self.planeCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "Y/Z (Out/Up)", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Length Scale (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.speedScaleLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Speed Scale (mm/s):", None, QtGui.QApplication.UnicodeUTF8))
        self.speedAxisCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.speedAxisCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.speedAxisCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.speedAxisCombo.setItemText(3, QtGui.QApplication.translate("LegToolMainWindow", "Any", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ikConfigTab), QtGui.QApplication.translate("LegToolMainWindow", "IK Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.mountingGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Mounting", None, QtGui.QApplication.UnicodeUTF8))
        self.gaitLegLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Leg:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LegToolMainWindow", "X (right) (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LegToolMainWindow", "Y (forward) (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("LegToolMainWindow", "Z (up) (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.bodyCogGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Body CoG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("LegToolMainWindow", "X (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("LegToolMainWindow", "Y (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("LegToolMainWindow", "Z (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.idlePositionGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Idle Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("LegToolMainWindow", "X (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("LegToolMainWindow", "Y (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("LegToolMainWindow", "Z (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.gaitGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Gait", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "Ripple", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("LegToolMainWindow", "Max cycle Time (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("LegToolMainWindow", "Lift height (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("LegToolMainWindow", "Swing percent:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("LegToolMainWindow", "Position margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LegToolMainWindow", "Body Z offset (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("LegToolMainWindow", "Leg order:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("LegToolMainWindow", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.staticEnableCheck.setText(QtGui.QApplication.translate("LegToolMainWindow", "Enable statically stable gait", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("LegToolMainWindow", "Center Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("LegToolMainWindow", "Stable Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("LegToolMainWindow", "Margin (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("LegToolMainWindow", "Statically Stable", None, QtGui.QApplication.UnicodeUTF8))
        self.gaitGraphGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Gait Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackBeginLabel.setText(QtGui.QApplication.translate("LegToolMainWindow", "Begin:", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackBeginCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackBeginCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Steady State", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackSingleButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackRepeatButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackSlowRepeatButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "0.1x Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackCaptureButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Capture Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("LegToolMainWindow", "X (mm/s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("LegToolMainWindow", "Y (mm/s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("LegToolMainWindow", "Body X (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("LegToolMainWindow", "Body Y (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("LegToolMainWindow", "Body Z (mm):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("LegToolMainWindow", "Pitch (deg):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("LegToolMainWindow", "Roll (deg):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("LegToolMainWindow", "Yaw (deg):", None, QtGui.QApplication.UnicodeUTF8))
        self.commandResetButton.setText(QtGui.QApplication.translate("LegToolMainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("LegToolMainWindow", "Rot (deg/s):", None, QtGui.QApplication.UnicodeUTF8))
        self.geometryGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.geometryFrameCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.geometryFrameCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "World", None, QtGui.QApplication.UnicodeUTF8))
        self.geometryFrameCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "Body", None, QtGui.QApplication.UnicodeUTF8))
        self.geometryProjectionCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "X/Y", None, QtGui.QApplication.UnicodeUTF8))
        self.geometryProjectionCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Y/Z", None, QtGui.QApplication.UnicodeUTF8))
        self.geometryProjectionCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "X/Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("LegToolMainWindow", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.commandGroup.setTitle(QtGui.QApplication.translate("LegToolMainWindow", "Command (click to set)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("LegToolMainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "Translation X", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Translation Y", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(3, QtGui.QApplication.translate("LegToolMainWindow", "Body X", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(4, QtGui.QApplication.translate("LegToolMainWindow", "Body Y", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(5, QtGui.QApplication.translate("LegToolMainWindow", "Body Z", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(6, QtGui.QApplication.translate("LegToolMainWindow", "Body Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(7, QtGui.QApplication.translate("LegToolMainWindow", "Body Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.commandXCombo.setItemText(8, QtGui.QApplication.translate("LegToolMainWindow", "Body Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("LegToolMainWindow", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("LegToolMainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(0, QtGui.QApplication.translate("LegToolMainWindow", "Translation X", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(1, QtGui.QApplication.translate("LegToolMainWindow", "Translation Y", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(2, QtGui.QApplication.translate("LegToolMainWindow", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(3, QtGui.QApplication.translate("LegToolMainWindow", "Body X", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(4, QtGui.QApplication.translate("LegToolMainWindow", "Body Y", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(5, QtGui.QApplication.translate("LegToolMainWindow", "Body Z", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(6, QtGui.QApplication.translate("LegToolMainWindow", "Body Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(7, QtGui.QApplication.translate("LegToolMainWindow", "Body Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.commandYCombo.setItemText(8, QtGui.QApplication.translate("LegToolMainWindow", "Body Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("LegToolMainWindow", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gaitConfigTab), QtGui.QApplication.translate("LegToolMainWindow", "Gait Configuration", None, QtGui.QApplication.UnicodeUTF8))

