# Copyright 2015 Josh Pieper, jjp@pobox.com.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('targetenv')

env = targetenv.Clone()

MODULES = [
    'STM32_USB_Device_Library/Core',
    'STM32_USB_Device_Library/Class/CDC',
    ]

SOURCES = []
libmiddlewares_include = []
for module in MODULES:
    SOURCES.extend(Glob('ST/' + module + '/Src/*.c'))
    includedir = 'ST/' + module + '/Inc'
    env.Append(CPPPATH=[includedir])
    libmiddlewares_include.append('#/Middlewares/' + includedir)

libmiddlewares = env.Library('middlewares', SOURCES)

Export('libmiddlewares')
Export('libmiddlewares_include')
