# Copyright 2015 Josh Pieper, jjp@pobox.com.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('targetenv')
Import('libmiddlewares_include')

env = targetenv.Clone()
env.Append(CPPPATH=libmiddlewares_include)
env.Append(CPPPATH=['#/gimbal'])

SOURCES = Glob('*.c')

# TODO jpieper: We disable these errors until I can fix them.
env.Append(CFLAGS=['-Wno-pointer-sign'])

libsrc = env.Library('src', SOURCES)

Export('libsrc')
